spring.application.name=madhavanspringboot
server.max-http-request-header-size=16KB

spring.datasource.url=jdbc:mysql://localhost:3306/madhan_springboot?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=MADHAVAN123@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop
